### ISSUE TITLE
Website User Interface Mockups

### ISSUE THREAD

**Issue by Xuanting85** [Valdarie/INF2001-P3-T4#14]
**Task Title ID:** #14

**What is the task about? Please describe in detail.**
This task is to create UI mockups for the workload management system using Figma. The process includes designing and visualising the various screens, layouts and elements that will comprise the system's UI.

**What are the goals of this task? Please describe in detail.**
The goal of this task is to provide a visual representation of how the workload management system will function from a user's perspective. This involves designing the UI in a way that is effectively communicates the system's functionality, user interactions and overall user experience.

**Success or completion criteria. Please describe in detail.**
- [x] Create comprehensive UI mockups that covers relevant screens, pages and interactions while ensuring visual clarity and consistency.
- [x] Ensures that all UI components are functional and working as intended. 
- [x]  Ensures that the UI mockups uses the relevant organisational colour scheme and follows the page layer specifications as stated in the User Interface Requirements

**Allocated Time:**

**Start date and end date of the task.**
Start Date: 10 September 2023
End Date: 23 September 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Seri Hanzalah Bte Haniffah

**The status of the task. (Usually in the initial column "To-Do")**
Completed

**What is the priority of this task?**
High

**Comment by Valdarie** [comment]
**Describe the work done in detail.**
We have started up with creating our UI mockups in Figma. This involves designing screens, layouts and elements to visualise system's user interface comprehensively. The mockups covered various aspects of the system including the Homepage, IT Login Page, Staff/Manager Login Page, IT Login Page, IT Create Account Page, Staff/Manager Login Page, Manager Home Page, Staff Home Page.

**Has this work been committed to the repo?**
No

**How does the work affect "4. Success or completion criteria"?**
The visual representation plays an important part to understand the system's functionality. The mockups guarantee that all UI components function as intended, providing a realistic user experience. The mockups serve as a critical reference for us during the implementation of the workload management system user interface

**Start date and end date of the work done.**
Start Date: 10 September 2023
End Date: 23 September 2023
