### ISSUE TITLE
Project Meeting 04: M1 Report Updates

### ISSUE THREAD

**Issue by Valdarie** [Valdarie/INF2001-P3-T4#21]
**Task Title ID:** [#21](https://github.com/Valdarie/INF2001-P3-T4/issues/21)

**What is the task about? Please describe in detail.**
Weekly project meeting to discuss and fix up the M1 Report based on previous feedbacks given.

**What are the goals of this task? Please describe in detail.**
The goal is to identify any mistakes or incorrect details written in the M1 Report. This includes discussions regarding the "Use-Case Diagram" as well as the various "Use-Case Descriptions" and project requirements 

**Success or completion criteria. Please describe in detail.**
- [x] Update Kanban board with issues and write description for each issues.
- [x] Completed Section 01 Introduction. This includes polishing the 1.1 Project scope, fixing the 1.2 Related Background, finish 1.3 Intended Audience and Document Overview and start writing on 1.4 References and Acknowledgments
- [x] Completed Section 02 Overall Description. This includes finishing up 2.1 Project Overview, starting on the System’s Architecture Diagram (Technical Architecture Diagram), 2.2 Project Functionality, 2.3 Assumptions and Dependencies
- [x] Completed Section 03 Intended Audience and Document Overview. This includes rewriting 3.1 User Interface Requirements, updating the 3.2 Functional Requirements and 3.4 Non-Functional Requirements, writing the fist draft of 3.4.1 Performance Requirements, as well as the 3.4.2 Safety and Security Requirements

**Allocated Time**: 3 hours

**Start date and end date of the task.**
Start Date: 19 September 2023
End Date: 19 September 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
@Valdarie 

**The status of the task. (Usually in the initial column "To-Do")**
COMPLETED

**What is the priority of this task?**
High

**Comment by Valdarie** [comment]
Photo taken by: @Valdarie 
Date Taken: 19 September 2023
Featuring all members (excluding @Valdarie camera man)
![image](https://github.com/Valdarie/INF2001-P3-T4/assets/31137223/b8dddc20-4b00-48aa-8f23-c59a3f7fd80a)

**Comment by Valdarie** [comment]
**Describe the work done in detail.**
We have worked on Section 01 Introduction, Section 02 Overall Description as well as Section 03 Intended Audience and Document Overview. 

**Has this work been committed to the repo?**
No.

**How does the work affect "4. Success or completion criteria"?**
We need to rework on our Use Case Diagrams as well as the Use Case Descriptions. 

**Start date and end date of the work done.**
Start Date: 19 September 2023
End Date: 19 September 2023

**Comment by Valdarie** [comment]
Sneak peak of our discussion contents
![Image](https://github.com/Valdarie/INF2001-P3-T4/assets/31137223/800a39d7-6730-41ff-89cb-344bbb63144b)

For UC1
![Image](https://github.com/Valdarie/INF2001-P3-T4/assets/113411728/dd7f7551-2334-4273-b6cc-d52688e36789)

**Comment by Xuanting85** [comment]
![Image](https://github.com/Valdarie/INF2001-P3-T4/assets/113411728/dd7f7551-2334-4273-b6cc-d52688e36789)
