### ISSUE TITLE
Software Estimation

### ISSUE THREAD

**Issue by Khanrasheed472** [Valdarie/INF2001-P3-T4#9]
**Task Title ID:** #9

**What is the task about? Please describe in detail.**
This task is about estimating the amount of time and effort needed for our software project. We want to figure out how long it will take and how many people we'll need to complete it successfully. This task can be done through calculations of Use Case Points (UCP).

**What are the goals of this task? Please describe in detail.**
The main goal of this task is to provide accurate estimates for our project. This will help us plan our work, allocate resources, and set realistic expectations for what we can achieve. In other words, knowing how much effort each task requires helps to make sure that everyone is assigned a fair amount of work, and that everyone has the resources they need to get their work done on time.

**Success or completion criteria. Please describe in detail.**
The success criteria for this task are:
- [x] Calculate the lower bound estimate for developer hours.
- [x] Calculate the upper bound estimate for developer hours.
- [x] Determine the weekly effort required per developer.
- [x] Document the start and end dates for the task.

**Allocated Time:** 4 Hrs

**Start date and end date of the task.**
Start Date: 21 September 2023
End Date: 22 September 2023

**Who is the owner? (Task's person-in-charge; task is to be created and maintained by owner)**
Bryon 

**The status of the task. (Usually in the initial column "To-Do")**
Completed

**What is the priority of this task?**
High Priority

**Comment by Khanrasheed472** [comment]
**Describe the work done in detail:**
In this task, we conducted detailed software estimation for our project. We followed the guidelines provided by Gustav Karner, the creator of UCP (Use Case Points), to estimate the developer-hours required. We calculated the Total Unadjusted Use Case Points(UUCW), Technical Complexity Factors (TCF), and Environmental Factor (EF) to determine the Use Case Points (UCP). Using the UCP, we carried out the Effort Estimations by calculating both lower and upper bound estimates based on the range of 15 to 30 hours for each UCP. Additionally, we determined the weekly effort per developer for our 9-week project timeline.

**Has this work been committed to the repo?**
No.

**How does the work affect "4. Success or completion criteria"?**
Upon completion of this task, we successfully fulfilled the Software estimation of the project. This allows us to estimate how much predicted effort we require to complete this entire project. After our calculations, we have calculated an _optimistic_ amount of _1005_ Hrs, and a _pessimistic_ amount of _2010_ Hrs.

**Start date and end date of the work done.**
  **- Start Date: 21 Sep 2023**
  **- End Date: 22 Sep 2023**
